---
title: "Meteorites Weekend Homework"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    css: ../../../styles.css
  pdf_document: default
---

# MVP

The goal of this homework is to produce a reproducible analysis of some meteorites. Rather than work solely in a Notebook, we're going to write an R cleaning script as well. By the end you'll create:

1. An .R file that cleans some data on meteorites.
2. A .Rmd file that takes your cleaned data and performs some analysis.

You will also write a short `README.md` that describes the structure of your project.

The data you want to clean is in the file called `meteorite_landings.csv`. It comes from NASA and has information on meteorites that have been found up to the year 2013. 

## The .R file

To clean the data please do the following.

1. Read the data into R
2. Change the names of the variables to follow our naming standards.
3. Split the column `GeoLocation` into latitude and longitude, the new latitude and longitude columns should be numeric.
4. Replace any missing values in latitude and longitude with zeros.
5. Remove meteorites less than 1000g in weight from the data.
6. Order the data by the year of discovery.

## The .Rmd file

In the .Rmd file please do the following.

1. Read the cleaned data into your environment.
2. Find the names and years found for the 10 largest meteorites in the data.
3. Find the average mass of meteorites that were recorded falling, vs. those which were just found.
4. Find the number of meteorites in each year, for every year since 2000.
5. Write a function called `get_meteorite_count()` that takes in two arguments: a dataframe and a year, and returns the phrase "In (input_year), there were (number of meteorites that year) meteorites." IF there are 1 or more meteorites that year. If there are no meteorites in the year, return the phrase "As far as we know, there were no meteorites that year".

## The README.md file

Make a file called `README.md`. In this file we just want you to describe the structure of your project, and write a general summary of your code.

